In [7]:
import numpy as np
import csv, sys
%matplotlib inline
import matplotlib.pyplot as plt

In [65]:
with open('input2.csv', 'rb') as csvfile:
    data = list(csv.reader(csvfile, delimiter=','))
csv_data = np.array(data, dtype=np.double)
csv_data

array([[  2.       ,  10.21027  ,   0.8052476],
       [  2.04     ,  13.07613  ,   0.9194741],
       [  2.13     ,  11.44697  ,   0.9083505],
       [  2.21     ,  14.43984  ,   0.8037555],
       [  2.29     ,  12.59622  ,   0.811357 ],
       [  2.38     ,  10.5199   ,   0.9489974],
       [  2.46     ,  12.89517  ,   0.9664505],
       [  2.54     ,  12.11692  ,   0.9288403],
       [  2.63     ,  16.76085  ,   0.86205  ],
       [  2.71     ,  11.20934  ,   0.9811632],
       [  2.79     ,  13.48913  ,   0.9883778],
       [  2.88     ,  11.85574  ,   1.004748 ],
       [  2.96     ,  11.54332  ,   1.001915 ],
       [  3.04     ,  12.90222  ,   0.9934899],
       [  3.13     ,  13.03542  ,   0.8974875],
       [  3.21     ,  11.88202  ,   0.8887256],
       [  3.29     ,  11.99685  ,   0.932307 ],
       [  3.38     ,  11.82981  ,   0.937784 ],
       [  3.46     ,  12.70158  ,   1.05032  ],
       [  3.54     ,  19.58748  ,   1.056727 ],
       [  3.63     ,  16.46093  ,   0.98

In [69]:
stddev = np.std(csv_data, axis=0)
stddev_tiles = np.tile(std_dev, (csv_data.shape[0],1))
stddev_tiles

array([[ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.14675477],
       [ 1.89948154,  6.11745394,  0.146

In [68]:
mean = np.mean(csv_data, axis=0)
mean_tiles = np.tile(mean, (csv_data.shape[0],1))
-mean_tiles

array([[ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.3066043 ,  -1.09646081],
       [ -5.21050633, -18.30660

In [71]:
scaled_data = np.divide(np.add(csv_data, -mean_tiles), stddev_tiles)
scaled_data

array([[ -1.69020138e+00,  -1.32348104e+00,  -1.98435264e+00],
       [ -1.66914301e+00,  -8.55008367e-01,  -1.20600314e+00],
       [ -1.62176166e+00,  -1.12132177e+00,  -1.28180034e+00],
       [ -1.57964490e+00,  -6.32087195e-01,  -1.99451994e+00],
       [ -1.53752814e+00,  -9.33457670e-01,  -1.94272265e+00],
       [ -1.49014679e+00,  -1.27286685e+00,  -1.00482876e+00],
       [ -1.44803004e+00,  -8.84589300e-01,  -8.85901788e-01],
       [ -1.40591328e+00,  -1.01180726e+00,  -1.14218102e+00],
       [ -1.35853193e+00,  -2.52679353e-01,  -1.59729605e+00],
       [ -1.31641518e+00,  -1.16016636e+00,  -7.85648146e-01],
       [ -1.27429842e+00,  -7.87496620e-01,  -7.36487222e-01],
       [ -1.22691707e+00,  -1.05450149e+00,  -6.24939228e-01],
       [ -1.18480032e+00,  -1.10557176e+00,  -6.44243541e-01],
       [ -1.14268356e+00,  -8.83436860e-01,  -7.01652919e-01],
       [ -1.09530221e+00,  -8.61663096e-01,  -1.35582178e+00],
       [ -1.05318545e+00,  -1.05020559e+00,  -1.4155261