In [141]:
import numpy as np
import csv, sys
%matplotlib inline
import matplotlib.pyplot as plt

In [159]:
with open('input2.csv', 'rb') as csvfile:
    data = list(csv.reader(csvfile, delimiter=','))
csv_data = np.array(data, dtype=np.double)
features = csv_data[:,[0,1]]
values = csv_data[:,2]
values

array([0.81, 0.92, 0.91, 0.80, 0.81, 0.95, 0.97, 0.93, 0.86, 0.98, 0.99,
       1.00, 1.00, 0.99, 0.90, 0.89, 0.93, 0.94, 1.05, 1.06, 0.98, 0.91,
       1.07, 1.03, 0.93, 0.93, 1.10, 0.99, 1.11, 1.06, 1.01, 1.04, 1.14,
       0.98, 1.06, 1.10, 1.17, 1.16, 1.01, 1.09, 1.10, 1.03, 1.08, 1.11,
       1.19, 1.09, 1.07, 1.17, 1.23, 1.06, 1.25, 1.25, 1.17, 1.09, 1.22,
       1.12, 1.12, 1.11, 1.31, 1.11, 1.18, 1.15, 1.14, 1.34, 1.33, 1.31,
       1.17, 1.16, 1.37, 1.17, 1.26, 1.37, 1.39, 1.32, 1.38, 1.21, 1.22,
       1.41, 1.30])

In [150]:
stddev = np.std(features, axis=0)
stddev

array([1.90, 6.12])

In [172]:
stddev_tiles = np.tile(stddev, (features.shape[0],1))
stddev_tiles

array([[1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90, 6.12],
       [1.90,

In [154]:
mean = np.mean(features, axis=0)
mean_tiles = np.tile(mean, (features.shape[0],1))
-mean_tiles

array([[-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -18.31],
       [-5.21, -

In [155]:
features = np.divide(np.add(features, -mean_tiles), stddev_tiles)
float_formatter = lambda x: "%.2f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})
features

array([[-1.69, -1.32],
       [-1.67, -0.86],
       [-1.62, -1.12],
       [-1.58, -0.63],
       [-1.54, -0.93],
       [-1.49, -1.27],
       [-1.45, -0.88],
       [-1.41, -1.01],
       [-1.36, -0.25],
       [-1.32, -1.16],
       [-1.27, -0.79],
       [-1.23, -1.05],
       [-1.18, -1.11],
       [-1.14, -0.88],
       [-1.10, -0.86],
       [-1.05, -1.05],
       [-1.01, -1.03],
       [-0.96, -1.06],
       [-0.92, -0.92],
       [-0.88, 0.21],
       [-0.83, -0.30],
       [-0.79, -0.51],
       [-0.75, -0.48],
       [-0.70, -0.66],
       [-0.66, -0.79],
       [-0.62, -0.77],
       [-0.57, -0.83],
       [-0.53, -0.86],
       [-0.48, -0.04],
       [-0.44, -0.01],
       [-0.40, -0.80],
       [-0.35, -0.46],
       [-0.31, -0.43],
       [-0.26, -0.17],
       [-0.22, -0.66],
       [-0.17, 0.54],
       [-0.13, -0.67],
       [-0.09, -0.65],
       [-0.04, 0.30],
       [-0.00, 1.19],
       [0.04, 0.05],
       [0.09, -0.56],
       [0.13, -0.37],
       [0.17, -0.45

In [156]:
beta = np.zeros((features.shape[0], features.shape[1]+1))
beta

array([[0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00],
 

0
1
2


array([[0.91, 0.72, 0.43, 0.21]])

In [169]:
beta[:,0] + np.sum(beta[:,[1,2]] * features, axis=1) - values

array([-0.81, -0.92, -0.91, -0.80, -0.81, -0.95, -0.97, -0.93, -0.86,
       -0.98, -0.99, -1.00, -1.00, -0.99, -0.90, -0.89, -0.93, -0.94,
       -1.05, -1.06, -0.98, -0.91, -1.07, -1.03, -0.93, -0.93, -1.10,
       -0.99, -1.11, -1.06, -1.01, -1.04, -1.14, -0.98, -1.06, -1.10,
       -1.17, -1.16, -1.01, -1.09, -1.10, -1.03, -1.08, -1.11, -1.19,
       -1.09, -1.07, -1.17, -1.23, -1.06, -1.25, -1.25, -1.17, -1.09,
       -1.22, -1.12, -1.12, -1.11, -1.31, -1.11, -1.18, -1.15, -1.14,
       -1.34, -1.33, -1.31, -1.17, -1.16, -1.37, -1.17, -1.26, -1.37,
       -1.39, -1.32, -1.38, -1.21, -1.22, -1.41, -1.30])

In [173]:
R = 0.5 * np.sum(np.square(beta[:,0] + np.sum(beta[:,[1,2]] * features, axis=1) - values)) / csv_data.shape[0]

In [174]:
alpha = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10]

iterations = 100




1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
